import localizationKeys from "./localization-keys";

const ar = {
  // auth
  [localizationKeys.login]: "تسجيل الدخول",
  [localizationKeys.signup]: "إنشاء حساب جديد",
  [localizationKeys.loginOrRegister]: "سجل",
  [localizationKeys.loginWithApple]: "تسجيل الدخول باستخدام Apple",
  [localizationKeys.loginwithGoogle]: "تسجيل الدخول باستخدام Google",
  [localizationKeys.loginwithFacebook]: "تسجيل الدخول باستخدام Facebook",
  [localizationKeys.signupwithApple]: "تسجيل الدخول باستخدام Apple",
  [localizationKeys.signupwithGoogle]: "تسجيل الدخول باستخدام Google",
  [localizationKeys.signupwithFacebook]: "تسجيل الدخول باستخدام Facebook",
  [localizationKeys.somethingWentWrongPleaseTryAgainLater]:
    "هناك خطأ ما يرجى المحاولة مرة أخرى في او وقت لاحق",
  [localizationKeys.rememberPassword]: "تذكر كلمة المرور",
  [localizationKeys.forgetPassword]: "نسيت كلمة المرور",
  [localizationKeys.name]: "الاسم",
  [localizationKeys.email]: "البريد الإلكتروني",
  [localizationKeys.phone]: "الهاتف",
  [localizationKeys.password]: "كلمة المرور",
  [localizationKeys.iAgreetotheTermsConditions]: "أنا موافق على البنود والشروط",
  [localizationKeys.createAccount]: "إنشاء حساب",
  [localizationKeys.aVerificationMailHasBeenSent]:
    "تم إرسال بريد تحقق إلى بريدك ، يرجى التحقق منه ....",
  [localizationKeys.thePasswordHasBeenSuccessfullyChanged]:
    "تم تغيير كلمة المرور بنجاح",
  [localizationKeys.backToHome]: "العودة إلى الصفحة الرئيسية",
  [localizationKeys.resetPassword]: "إعادة تعيين كلمة المرور",
  [localizationKeys.newPassword]: "كلمة مرور جديدة",
  [localizationKeys.reEnterPassword]: "إعادة إدخال كلمة المرور",
  [localizationKeys.theEmailAddressForThisAccountHasNotYetBeenVerified]:
    "لم يتم التحقق من عنوان البريد الإلكتروني لهذا الحساب حتى الآن. يرجى التحقق من صندوق الوارد الخاص بك. إذا لم تتمكن من العثور على هذا البريد الإلكتروني",
  [localizationKeys.resendMailAgain]: "إعادة إرسال البريد مرة أخرى",
  [localizationKeys.or]: "أو",
  [localizationKeys.backToLogin]: "الرجوع إلى تسجيل الدخول",
  [localizationKeys.sentVerification]: "إرسال التحقق",
  [localizationKeys.securityDeposit]: "بلغ التأمين",

  // home
  [localizationKeys.subscribedSuccessfully]: "تم الاشتراك بنجاح",
  [localizationKeys.unsubscribedSuccessfully]: "لقد تم إلغاء اشتراكك بنجاح",
  [localizationKeys.unsubscriptionFailed]: "فشل إلغاء الاشتراك",
  [localizationKeys.myBids]: "مزاياداتي",
  [localizationKeys.categories]: "الفئات",
  [localizationKeys.watchlist]: "قائمة المراقبة",
  [localizationKeys.faqs]: "الأسئلة الشائعة",
  [localizationKeys.support]: "الدعم",
  [localizationKeys.arabic]: "عربي",
  [localizationKeys.english]: "English",
  [localizationKeys.sellNow]: "بيع الآن",
  [localizationKeys.search]: "بحث ...",
  [localizationKeys.registerNow]: "سجل الآن",
  [localizationKeys.profile]: "الملف الشخصي",
  [localizationKeys.viewDetails]: "عرض التفاصيل",
  [localizationKeys.bidNow]: "المزايدة الآن",
  [localizationKeys.popularCategories]: "الفئات الشائعة",
  [localizationKeys.results]: "من النتائج",
  [localizationKeys.seeAll]: "عرض الكل",
  [localizationKeys.seeLess]: "عرض أقل",
  [localizationKeys.brand]: "العلامة التجارية",
  [localizationKeys.sellingType]: "نوع البيع",
  [localizationKeys.auction]: "مزاد",
  [localizationKeys.buyNow]: "اشتري الآن",
  [localizationKeys.expiredAuctions]: "المزادات المنتهية",
  [localizationKeys.deliveryPolicy]: "سياسة التسليم ",
  [localizationKeys.expectedDeliveryDays]: "أيام التسليم المتوقعة",
  [localizationKeys.deliveryFees]: "رسوم التوصيل",
  [localizationKeys.locatedIn]: "يقع في ",
  [localizationKeys.PolicyDescription]: "وصف السياسة",
  [localizationKeys.auctionState]: "حالة المزاد",
  [localizationKeys.comingSoon]: "قريباً",
  [localizationKeys.liveAuction]: "المزاد المباشر",
  [localizationKeys.location]: "الموقع",
  [localizationKeys.condition]: "الحالة",
  [localizationKeys.new]: "جديد",
  [localizationKeys.used]: "مستعملة",
  [localizationKeys.openBox]: "صندوق مفتوح",
  [localizationKeys.price]: "السعر",
  [localizationKeys.createAuctionNow]: "إنشاء مزاد الآن",
  [localizationKeys.weAreAlwaysHereToHelpYou]: "نحن دائمًا هنا لمساعدتك ...",
  [localizationKeys.subscribeNowToGetNewOffersAndUpdates]:
    "اشترك الآن للحصول على عروض وتحديثات جديدة",
  [localizationKeys.writeYourMail]: "اكتب بريدك ...",
  [localizationKeys.subscribe]: "اشتراك",
  [localizationKeys.sellingOnAllatre]: "البيع على Allatre",
  [localizationKeys.sellerCenter]: "مركز البائع",
  [localizationKeys.sellForCharity]: "بيع للجمعيات الخيرية",
  [localizationKeys.businessTools]: "أدوات العمل",
  [localizationKeys.createAuction]: "إنشاء مزاد",
  [localizationKeys.listProduct]: "اضف اعلان",
  [localizationKeys.price]: "سعر",
  [localizationKeys.myAccount]: "حسابي",
  [localizationKeys.iamBiddingOn]: "أنا أقوم بالمزايدة على",
  [localizationKeys.iHaveBought]: "لقد اشتريت",
  [localizationKeys.bidsIHaveReceived]: "العطاءات التي استلمتها",
  [localizationKeys.iHaveSold]: "لقد بعت",
  [localizationKeys.allRightsReserved]: "جميع الحقوق محفوظة.",
  [localizationKeys.upComingAuctions]: "المزادات القادمة",
  [localizationKeys.totalBids]: "إجمالي المزايدات",
  [localizationKeys.yourPendingPaymentsAreListedHere]:
    "تظهر مدفوعاتك المعلقة هنا",
  [localizationKeys.bid]: "مزاد",
  [localizationKeys.startingTime]: "وقت البدء",
  [localizationKeys.endingTime]: "نهاية الوقت",
  [localizationKeys.days]: "أيام",
  [localizationKeys.hrs]: "ساعة",
  [localizationKeys.min]: "دقيقة",
  [localizationKeys.sec]: "ثانية",
  [localizationKeys.achieveVisuallyImpressiveAuctionAttractBiddersMoreEasily]:
    "حقق مزادًا مثيرًا للإعجاب من الناحية المرئية وجذب المزايدين بسهولة أكبر.",
  [localizationKeys.YouCanMakeYourAuctionAdPriorityAndDisplayItFirstToIncreaseBidder]:
    "يمكنك جعل إعلان المزاد الخاص بك أولوية وعرضه أولاً لزيادة العطاء",
  [localizationKeys.participationAndAttractMoreBidders]:
    "المشاركة وجذب المزيد من العطاءات",
  [localizationKeys.CreateyourAdNow]: "أنشئ إعلانك الآن",
  [localizationKeys.PopularPicksPerfectChoices]:
    "اختيارات رائجة ، اختيارات مثالية",
  [localizationKeys.Grid]: "الشبكة",
  [localizationKeys.List]: "قائمة",
  [localizationKeys.ThereAreAuctionsCurrentlyYouCanCreateYourOwnAuctionRightNow]:
    "لا توجد مزادات حاليًا. يمكنك إنشاء مزادك الخاص الآن",
  [localizationKeys.BidWinRepeat]: "المزايدة ، الفوز ، التكرار!",
  [localizationKeys.ComingSoonGetReadytoBid]: "قريبًا: استعد للمزايدة!",
  [localizationKeys.DontWaitBuyNow]: "لا تنتظر ، اشتر الآن!",
  [localizationKeys.Bysubscribingyounevermissbeat]: "لا تنتظر ، اشتر الآن!",
  [localizationKeys.Bysubscribingyounevermissbeat]:
    "من خلال الاشتراك ، لن يفوتك أي شيء أبدًا.",
  [localizationKeys.Stayinformedaboutourlatestproductarrivalsspecialpromotionsandseasonalsales]:
    "ابق على اطلاع بأحدث المنتجات التي وصلتنا ، والعروض الترويجية الخاصة ، والمبيعات الموسمية.",
  [localizationKeys.termsAndCondition]: "الشروط والأحكام",
  [localizationKeys.iAcceptThe]: "انا اقبل",
  [localizationKeys.sell]: "بيع",
  [localizationKeys.timing]: "توقيت",
  [localizationKeys.selectTheDeliveryType]: "حدد نوع التسليم",
  [localizationKeys.sellerAddress]: "عنوان البائع",
  // status
  [localizationKeys.activeNow]: "نشط الآن",
  [localizationKeys.Scheduled]: "  مجدولة",
  [localizationKeys.sold]: "مباع",
  [localizationKeys.pending]: "معلق",
  [localizationKeys.waitingForPayment]: "في انتظار الدفع",
  [localizationKeys.soldOut]: "نفذ",
  [localizationKeys.expired]: "منتهي",
  [localizationKeys.inProgress]: "في تَقَدم",
  [localizationKeys.close]: "يغلق",
  // Breadcrumb
  [localizationKeys.home]: "الصفحة الرئيسية",
  [localizationKeys.productDetails]: "تفاصيل المنتج",
  [localizationKeys.auctionDetails]: "تفاصيل المزاد",
  [localizationKeys.shippingDetails]: "تفاصيل الشحن",
  [localizationKeys.paymentDetails]: "تفاصيل الدفع",
  [localizationKeys.myAuctions]: "مزاداتي",
  [localizationKeys.activeAuctions]: "المزادات النشطة",
  [localizationKeys.scheduledAuctions]: "المزادات المجدولة",
  [localizationKeys.soldAuctions]: "المزادات المباعة",
  [localizationKeys.pendingAuctions]: "المزادات المعلقة",
  [localizationKeys.expiredAuctions]: "المزادات المنتهية",
  [localizationKeys.payDeposite]: "إيداع الدفع",
  [localizationKeys.inOrderToCompletePublishingYourAdSuccessfullyPleasePayTheAdFeeAndStartReceivingBidsImmediately]:
    "لكي تتمكن من إتمام نشر مزادك بنجاح، يرجى دفع رسوم المزاد والبدء في تلقي العطاءات على الفور.",
  [localizationKeys.adPreview]: "معاينة الإعلان",
  [localizationKeys.auctionFee]: "رسوم المزاد",
  [localizationKeys.feesRefundedAfterAuctionCompletion]:
    "يتم استرداد الرسوم بعد انتهاء المزاد",
  [localizationKeys.ifYouWantToCheckAuctionsPolicyYouCanCheck]:
    "إذا كنت تريد التحقق من سياسة المزاد، يمكنك التحقق",
  [localizationKeys.paymentMethod]: "طريقة الدفع",
  [localizationKeys.viewPendingPayments]: "عرض المدفوعات المعلقة",
  [localizationKeys.continuePayment]: "متابعة الدفع",
  [localizationKeys.yourPaymentDetailsAreSaved]:
    "تم حفظ تفاصيل الدفع الخاصة بك",
  [localizationKeys.auctionStartingPrice]: "سعر بداية المزاد",
  [localizationKeys.auctionStartingDate]: "تاريخ بدء المزاد",
  [localizationKeys.auctionEndingDate]: "تاريخ انتهاء المزاد",
  [localizationKeys.inOrderToCompleteSubmittingYourBidPleasePayTheDepositForTheAuction]:
    "من أجل إكمال عملية المزايدة، يرجى دفع وديعة المزاد",
  [localizationKeys.pleaseNoticeThatTheBiddingDepositWillBeCapturedUntilTheAuctionIsCompletedWithin3WorkingDaysIfYouWinsTheAuctionTheWebsiteWillWithdrawTheDeposit]:
    "يرجى ملاحظة أن وديعة المزايدة سيتم حجزها حتى اكتمال المزاد في غضون ثلاثة أيام عمل. إذا فزت بالمزاد، فسوف يقوم الموقع بسحب الوديعة.",
  [localizationKeys.ShopSustainableChoosePreOwned]:
    "تسوق مستدامًا: اختر السلع المستعملة",
  [localizationKeys.getItNewFeeltheDifference]:
    "احصل عليه جديدًا، واشعر بالفرق",
  [localizationKeys.locationNotAvailable]: "الموقع غير متاح",

  // create auctions
  [localizationKeys.drafts]: "المسودات",
  [localizationKeys.proceed]: "متابعة",
  [localizationKeys.successDelete]: "تم حذف مزادك من صياغتك بنجاح",
  [localizationKeys.errorDelete]:
    "عفوًا ، آسف لحدوث خطأ ما ، يرجى التأكد من صحة كل شيء والمحاولة مرة أخرى",
  [localizationKeys.areYouSureYouWantToDeleteThisDraft]:
    "هل أنت متأكد أنك تريد حذف هذه المسودة",
  [localizationKeys.confirmDeletedraft]: "تأكيد حذف المسودة",
  [localizationKeys.cancel]: "إلغاء",
  [localizationKeys.logOut]: "تسجيل الخروج",
  [localizationKeys.areYouSureYouWantToLogOut]:
    "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  [localizationKeys.confirmLogout]: "تأكيد تسجيل الخروج",
  [localizationKeys.skip]: "يتخطى",
  [localizationKeys.YesISentIt]: "نعم لقد ارسلته",
  [localizationKeys.yesDelete]: "نعم ، احذف",
  [localizationKeys.locationIsRequired]: "الموقع مطلوب",
  [localizationKeys.editLocation]: "تعديل الموقع",
  [localizationKeys.inOrderToFinishTheProcedureWeHaveToGetAccessTo]:
    "من أجل إنهاء الإجراء ، علينا الوصول إلى",
  [localizationKeys.yourLocationYouCanManageThemLater]:
    "موقعك. يمكنك إدارتها لاحقًا.",
  [localizationKeys.manageYouAddresses]: "إدارة عناوينك",
  [localizationKeys.country]: "دولة",
  [localizationKeys.city]: "المدينة",
  [localizationKeys.address]: "العنوان",
  [localizationKeys.addressLabel]: "علامة للعنوان",
  [localizationKeys.mobile]: "Mobile",
  [localizationKeys.zipCode]: "الرمز البريدي",
  [localizationKeys.successAddLocatons]: "إضافة موقع النجاح",
  [localizationKeys.add]: "إضافة",
  [localizationKeys.selectCountry]: "تحديد البلد",
  [localizationKeys.selectCity]: "اختر المدينة",
  [localizationKeys.wirteYourAddress]: "اكتب عنوانك",
  [localizationKeys.exHome]: "مثال:  المنزل",
  [localizationKeys.enterPostalZipCode]: "أدخل الرمز البريدي",
  [localizationKeys.building]: "أبراج جلفار، مكتب رقم 504,",
  [localizationKeys.place]: "رأس الخيمة,",
  [localizationKeys.uae]: "الإمارات العربية المتحدة",
  // product details
  [localizationKeys.itemDetails]: "تفاصيل السلعة",
  [localizationKeys.itemName]: "اسم العنصر",
  [localizationKeys.category]: "الفئة",
  [localizationKeys.subCategory]: "فئة فرعية",
  [localizationKeys.itemDescription]: "وصف العنصر",
  [localizationKeys.writeItemDescription]: "اكتب وصف العنصر ....",
  [localizationKeys.addMedia]: "إضافة وسائط",
  [localizationKeys.from3upto5photos]: "( من 3 إلى 5 صور )",
  [localizationKeys.itemCondition]: "حالة العنصر",
  [localizationKeys.saveAsDraft]: "حفظ كمسودة",
  [localizationKeys.next]: "التالي",
  [localizationKeys.youCanOnlySelectUpToFiveImages]:
    "يمكنك تحديد ما يصل إلى خمس صور فقط.",
  [localizationKeys.setAsCover]: "تعيين كصورة غلاف",
  [localizationKeys.cover]: "صورة غلاف",
  //List product
  [localizationKeys.call]: "يتصل",
  [localizationKeys.chat]: "محادثة",
  [localizationKeys.sellingPrice]: "سعر البيع",
  [localizationKeys.listed]: "مُدرج",
  [localizationKeys.listedProduct]: "المنتج المدرج",
  [localizationKeys.findAndReachTheProduct]: "البحث عن المنتج والوصول إليه",
  [localizationKeys.theBestDealsYouMissed]: "أفضل الصفقات التي فاتتك",
  [localizationKeys.callNow]: "اتصل الان",
  [localizationKeys.contactNumber]: "رقم التواصل",
  [localizationKeys.youCanConnectOn]: "يمكنك الاتصال على:",
  [localizationKeys.DontForgetToMention]: "لا تنسى أن تذكر",
  [localizationKeys.alletre]: "آلي تري",
  [localizationKeys.whenYouCall]: "عندما تتصل!",
  // auction details
  [localizationKeys.quickAuction]: "المزاد السريع",
  [localizationKeys.maximumDurationMustBeDay]:
    "يجب أن تكون المدة القصوى باليوم",
  [localizationKeys.longAuction]: "المزاد الطويل",
  [localizationKeys.durationMoreThanOneDayFromStartingDate]:
    "المدة أكثر من يوم واحد من تاريخ البدء",
  [localizationKeys.longAuction]: "المزاد الطويل",
  [localizationKeys.Hrs]: "ساعات.",
  [localizationKeys.auctionDuration]: "مدة المزاد",
  [localizationKeys.scheduleBid]: "مزاد مجدول",
  [localizationKeys.optional]: "(اختياري)",
  [localizationKeys.unlessStartTimeAndDateAreChosenYourListingBecomesActiveImmediately]:
    "ما لم يتم اختيار وقت وتاريخ البدء ، تصبح قائمتك نشطة على الفور.",
  [localizationKeys.amountThatYouCanSellWithoutAuction]:
    "المبلغ الذي يمكنك بيعه دون مزاد",
  [localizationKeys.youCanGiveHereYourDeliveryRelatedPolicy]:
    "يمكنك تقديم سياسة التسليم الخاصة بك هنا, ",
  [localizationKeys.startDate]: "تاريخ البدء",
  [localizationKeys.howManyDaysWillItTakeForTheDeliveryAfterAuctionExpired]:
    "كم يوما سيستغرق التسليم بعد انتهاء المزاد؟",
  [localizationKeys.youCanGiveHereYourReturnRelatedPolicy]:
    "يمكنك تقديم سياسة الإرجاع الخاصة بك هنا ",
  [localizationKeys.youCanGiveHereYourWarrantyRelatedPolicy]:
    "يمكنك تقديم سياسة الضمان الخاصة بك هنا ",
  [localizationKeys.includingDeliveryDateAndOthers]:
    "بما في ذلك تاريخ التسليم وغيرها...",
  [localizationKeys.time]: "الوقت",
  [localizationKeys.NumberOfDays]: "عدد الأيام",
  [localizationKeys.DeliveryFees]: "رسوم التوصيل",
  [localizationKeys.Amount]: "كمية",
  [localizationKeys.pricing]: "التسعير",
  [localizationKeys.startPrice]: "سعر البداية",
  [localizationKeys.purchasingPrice]: "سعر الشراء",
  [localizationKeys.DeliveryDescription]: "وصف التسليم",
  [localizationKeys.PleaseGiveTheDescription]: "يرجى تقديم وصفك",
  [localizationKeys.minimum30MoreThanStartingBid]:
    "الحد الأدنى: 30٪ أكثر من عرض السعر المبدئي",
  [localizationKeys.purchasingPriceMustBeMoreThanOrEqual30OfMinimumPrice]:
    "يجب أن يكون سعر الشراء أكبر من أو يساوي 30٪ من الحد الأدنى للسعر",
  [localizationKeys.whyWaitingBuyItNowOnThisPrice]:
    "لماذا الانتظار؟ اشتري الآن على هذا السعر!",
  [localizationKeys.similarProducts]: "منتجات مماثلة",
  [localizationKeys.exploreRelatedFind]: "استكشاف البحث عن ذات الصلة",
  // shiping details
  [localizationKeys.locationDetails]: "تفاصيل الشحن",
  [localizationKeys.addAddress]: "إضافة عنوان",
  [localizationKeys.successUpdateLocation]: "تم تحديث الموقع بنجاح.",
  [localizationKeys.confirmDeleteAddress]:
    "هل أنت متأكد من أنك تريد حذف هذا العنوان؟",
  [localizationKeys.addressDeletedSuccessfully]: "تم حذف العنوان بنجاح",
  [localizationKeys.errorDeletingAddress]: "خطأ في حذف العنوان",
  [localizationKeys.deleteAddress]: "حذف العنوان",
  [localizationKeys.cannotDeleteMainAddress]: "لا يمكن حذف العنوان الرئيسي",
  [localizationKeys.confirmDeleteAddressHeading]: " تأكيد حذف العنوان",
  // payment details
  [localizationKeys.paymentMethod]: "طريقة الدفع",
  [localizationKeys.backToHome]: "العودة للرئيسية",
  [localizationKeys.yourPurchaseHasBeenSuccessfullyCompleted]:
    "لقد تم إتمام عملية الشراء الخاصة بك بنجاح",
  [localizationKeys.yourDepositHasBeenSuccessfullyTransferredAndYourAuctionIsActiveNow]:
    "إيداعك تم نقله بنجاح ومزادك مفعل الآن",
  [localizationKeys.paymentSuccess]: "نجاح الدفع",
  [localizationKeys.yourBidHasBeenSuccessfullyPlaced]: "لقد تم وضع عرضك بنجاح",
  [localizationKeys.viewBids]: "عرض العطاءات",
  [localizationKeys.viewPurchased]: "عرض المشتريات",
  [localizationKeys.viewAuction]: "عرض المزادات",
  // profile
  [localizationKeys.online]: "متصل",
  [localizationKeys.logout]: "تسجيل الخروج",
  [localizationKeys.profileSettings]: "إعدادات الملف الشخصي",
  [localizationKeys.completeYourProfileToMakeYourActionsEasier]:
    "أكمل ملفك الشخصي لتسهيل إجراءاتك",
  [localizationKeys.completeNowMasg]:
    "يوفر حسابك حاليًا إمكانية الوصول إلى التحديثات والعناصر المحفوظة وتفاصيل البيع والميزات الأخرى. للمزايدة والشراء والبيع باستخدام Alle-tre ، يرجى قضاء بعض الوقت لملء معلومات ملفك الشخصي.",
  [localizationKeys.completeNow]: "أكمل الآن",
  [localizationKeys.editPhoto]: "تحرير الصورة",
  [localizationKeys.uploadPhoto]: "تحميل الصورة",
  [localizationKeys.dropYourPhotoHereToInstantlyUploadIt]:
    "أفلت صورتك هنا لتحميلها على الفور",
  [localizationKeys.save]: "حفظ",
  [localizationKeys.selectAfile]: "حدد ملفًا",
  [localizationKeys.edit]: "تحرير",
  [localizationKeys.contactUs]: "اتصل بنا",
  [localizationKeys.editUserName]: "تحرير اسم المستخدم",
  [localizationKeys.personalDetails]: "التفاصيل الشخصية",
  [localizationKeys.userName]: "اسم المستخدم",
  [localizationKeys.changePassword]: "تغيير كلمة المرور",
  [localizationKeys.editPassword]: "تحرير كلمة المرور",
  [localizationKeys.oldPassword]: "كلمة المرور القديمة",
  [localizationKeys.newPassword]: "كلمة المرور الجديدة",
  [localizationKeys.verified]: "تم التحقق منه",
  [localizationKeys.eMail]: "البريد الإلكتروني",
  [localizationKeys.phoneNumber]: "رقم الهاتف",
  [localizationKeys.editPhoneNumber]: "تحرير رقم الهاتف",
  [localizationKeys.loginService]: "خدمة تسجيل الدخول",
  [localizationKeys.loginServiceMaseg]:
    "حساب Alla-tre الخاص بك ليس لديه خدمة تسجيل دخول خارجية. قم بتوصيل الحسابات الآن للوصول السريع والآمن",
  [localizationKeys.connected]: "متصل",
  [localizationKeys.connectedWithApple]: "متصل مع Apple",
  [localizationKeys.connectWithGoogle]: "متصل مع Google",
  [localizationKeys.connectWithFacebook]: "متصل مع Facebook",
  [localizationKeys.addressBook]: "دفتر العناوين",
  [localizationKeys.addressBookmasg]:
    "إدارة عناوينك للحصول على تجربة دفع سريعة وسهلة",
  [localizationKeys.default]: "افتراضي",
  [localizationKeys.delete]: "حذف",
  [localizationKeys.makeDefault]: "جعله افتراضيًا",
  [localizationKeys.the]: " ال",
  [localizationKeys.yourWatchlist]: "قائمة المراقبة الخاصة بك",
  [localizationKeys.thereAreNoWatchlistYet]: "لا توجد قائمة المراقبة حتى الآن.",
  [localizationKeys.ChangedDefaultAdrress]: " تغيير العنوان الافتراضي",
  [localizationKeys.invalidLocationId]: "معرف الموقع غير صالح",
  [localizationKeys.accessBlocked]: "تم حظر الوصول",
  [localizationKeys.yourAccountIsBlockedByAdminPleaseContactSupport]:
    "تم حظر حسابك من قبل المسؤول. يرجى الاتصال بالدعم.",
  // myauctions
  [localizationKeys.createNow]: "أنشئ الآن",
  [localizationKeys.thereAreNoAuctionsCurrentlyMakeYourFirstAuctionRightAway]:
    "لا توجد مزادات حاليًا. قم بإجراء مزادك الأول على الفور.",
  [localizationKeys.totalAuctions]: "إجمالي المزادات",
  [localizationKeys.active]: "نشط",
  [localizationKeys.cancelled]: "ملغي",
  [localizationKeys.total]: "إجمالي",
  [localizationKeys.totalActive]: "إجمالي المزادات النشطة ..",
  [localizationKeys.totalCancel]: "إجمالي إلغاء المزادات.",
  [localizationKeys.youCanCreateOne]: "يمكنك إنشاء واحد",
  [localizationKeys.oppsActive]: "عفوًا ، لا توجد مزادات نشطة حتى الآن.",
  [localizationKeys.oppsCancelled]:
    "عفواً، لا توجد مزادات تم إلغاؤها حتى الآن.",
  [localizationKeys.lastPrice]: "آخر سعر",
  [localizationKeys.startingPrice]: "السعر المبدئي",
  [localizationKeys.startingDate]: "تاريخ البدء",
  [localizationKeys.pendingDeposit]: "إيداع معلق",
  [localizationKeys.purchasePrice]: " سعر الشراء",
  [localizationKeys.endingDate]: " تاريخ الانتهاء",
  [localizationKeys.endingTime]: " وقت الانتهاء",
  [localizationKeys.totalScheduled]: "إجمالي المزادات المجدولة ..",
  [localizationKeys.opsScheduled]: "عفوًا ، لا توجد مزادات مجدولة بعد",
  [localizationKeys.totalDraft]: "إجمالي مزادات المسودة ..",
  [localizationKeys.opsDraft]: "عفوًا ، لا توجد مزادات منتهية الصلاحية بعد.",
  [localizationKeys.totalSold]: "إجمالي المزادات المباعة ..",
  [localizationKeys.opsSold]: "عفوًا ، لا توجد مزادات مباعة بعد.",
  [localizationKeys.totalPending]: "إجمالي المزادات المعلقة ..",
  [localizationKeys.opsPending]: "عفوًا ، لا توجد عمليات بيع معلقة حتى الآن.",
  [localizationKeys.totalExpired]: "إجمالي المزادات المنتهية الصلاحية ...",
  [localizationKeys.watingForPaymentAuctions]: "في انتظار مزادات الدفع ...",
  [localizationKeys.cancelTheAuction]: "إلغاء المزاد؟",
  [localizationKeys.Warning]: "تحذير",
  [localizationKeys.PaymentSelection]: "اختيار الدفع",
  [localizationKeys.walletPayment]: "الدفع عن طريق المحفظة",
  [localizationKeys.BankTransfer]: "التحويل البنكي",
  [localizationKeys.BankTransferDetails]: "تفاصيل التحويل البنكي",
  [localizationKeys.onlinePayment]: "الدفع عبر الإنترنت",
  [localizationKeys.WhichPaymentMethodWouldYouLikeToSelect]:
    "ما هي طريقة الدفع التي ترغب في اختيارها؟",
  [localizationKeys.OK]: "نعم",
  [localizationKeys.didYouSendTheItemForDelivery]: "هل أرسلت العنصر للتسليم؟",
  [localizationKeys.sendMessageToBuyer]: "إرسال رسالة إلى المشتري",
  [localizationKeys.Message]: "رسالة...",
  [localizationKeys.CancellAuctionWarningMessageWithBidders]:
    "سيؤدي إلغاء المزاد إلى خسارة وديعة الضمان الخاصة بك",
  [localizationKeys.CancellAuctionWarningMessageWithZeroBidders]:
    "هل أنت متأكد من إلغاء المزاد..؟",
  [localizationKeys.ContinueToCancel]: "متابعة الإلغاء؟",
  [localizationKeys.discontinue]: "توقف",
  [localizationKeys.YouSuccessfullyCancelledTheAuction]:
    "تم إلغاء المزاد بنجاح..!",
  [localizationKeys.YouHaveSuccessfullyNotifiedTheWinner]:
    "لقد قمت بإخطار الفائز بنجاح",

  // mybids
  [localizationKeys.Youarenotbiddingonanyitems]:
    "أنت لا تقدم عطاءات على أي عناصر.",
  [localizationKeys.Checkactiveauctionstostartbidding]:
    "تحقق من المزادات النشطة لبدء تقديم العطاءات",
  [localizationKeys.inProgress]: "قيد التقدم",
  [localizationKeys.waitingForDelivery]: "بانتظار الطلبية",
  [localizationKeys.completed]: "مكتمل",
  [localizationKeys.ThereIsNoBidsYetInProgressAuctionsRightNow]:
    "لا توجد عطاءات حتى الآن مزادات قيد التقدم في الوقت الحالي",
  [localizationKeys.youHaveNotPlacedAnyBidsAtThisTime]:
    "لم تقم بوضع أي عروض في هذا الوقت",
  [localizationKeys.startBidding]: "بدء المزايدة",
  [localizationKeys.thereAreNoActiveBidsAtTheMomentPlaceYourFirstBidNow]:
    "لا توجد عروض نشطة في الوقت الحالي. قم بتقديم عرضك الأول الآن!",
  [localizationKeys.increaseBid]: "زيادة العطاء",
  [localizationKeys.inPrsubmitNewBidogress]: "تقديم عطاء جديد",
  [localizationKeys.ThereIsNoBidsYetPendingAuctionsRightNow]:
    "لا توجد عطاءات بعد المزادات المعلقة في الوقت الحالي",
  [localizationKeys.completePayment]: "إتمام الدفع",
  [localizationKeys.ThereIsNoBidsYetOnWaitingForDeliveryAuctionsRightNow]:
    "لا توجد عروض حتى الآن في انتظار مزادات التسليم في الوقت الحالي",
  [localizationKeys.confirmDelivery]: "تأكيد الاستلام",
  [localizationKeys.deliveryByCompany]: "التوصيل عن طريق الشركة",
  [localizationKeys.AnyCompliants]: "أي شكاوى؟",
  [localizationKeys.sellerContactDetails]: "تفاصيل الاتصال بالبائع",
  [localizationKeys.buyerContactDetails]: "تفاصيل الاتصال بالمشتري",
  [localizationKeys.unSubscribe]: "الغاء الاشتراك",
  [localizationKeys.ThereIsNoBidsYetExpiredAuctionsRightNow]:
    "لا توجد عروض حتى الآن مزادات منتهية الصلاحية",
  [localizationKeys.ThereIsNoBidsyetCompletedAuctionsRightNow]:
    "لا توجد عطاءات بعد المزادات المكتملة في الوقت الحالي",
  [localizationKeys.ThereIsNoBidsyetCancelledAuctionsRightNow]:
    "لا يوجد عروض حتى الآن تم إلغاء المزادات الآن",
  [localizationKeys.submitNewBid]: "تقديم مزايدة جديد",
  [localizationKeys.AnyObjection]: "أي اعتراضات؟",
  [localizationKeys.AllMyBids]: "كل عرضي",
  [localizationKeys.InProgress]: "قيد التنفيذ",
  [localizationKeys.Pending]: "المعلقه",
  [localizationKeys.completedAuction]: "المزاد المكتمل",
  [localizationKeys.cancelledAuctions]: "المزادات الملغية",
  //deleveryIssueReportModal
  [localizationKeys.NotDeliveredYet]: "لم يتم التسليم بعد؟",
  [localizationKeys.ProductIsNotAsShownInPicture]:
    "المنتج ليس كما هو موضح في الصورة؟",
  [localizationKeys.DoesProductHaveAnyIssueWhichIsNotMentionedInTheDescription]:
    "هل هناك أي مشكلة في المنتج غير المذكورة في الوصف؟",
  [localizationKeys.Others]: "آحرون؟",
  [localizationKeys.tellUsYourProblem]: "أخبرنا مشكلتك..؟",
  [localizationKeys.Description]: "وصف",
  [localizationKeys.uploadImages]: "تحميل الصور",
  [localizationKeys.YouCanSelectMultipleImagestogether]:
    "يمكنك تحديد صور متعددة معًا",
  [localizationKeys.Submit]: "ادفع",
  [localizationKeys.PleaseSelectAnyOption]: "الرجاء اختيار أي خيار..!",
  [localizationKeys.PleaseGiveTheDescription]: "من فضلك أعط الوصف..!",
  [localizationKeys.SorryYourSubmissionHasFailedPleaseTryAgainLater]:
    "عذرا، لقد فشل إرسال طلبك. يرجى المحاولة مرة أخرى لاحقًا..!",
  [localizationKeys.ThankYouForYourSubmission]: "شكرا لك على تقديمك..!",
  //  Purchased
  [localizationKeys.Purchased]: "مشترياتي",
  [localizationKeys.yourPurchased]: "مشترياتي",
  [localizationKeys.ThereAreNoPurchasedYet]: "لا يوجد مشتريات حتى الآن",
  // details
  [localizationKeys.reviews]: "مراجعات",
  [localizationKeys.timeLeft]: "الوقت المتبقي",
  [localizationKeys.submitBid]: "إرسال مزايدتك",
  [localizationKeys.description]: "الوصف",
  [localizationKeys.series]: "رقم تسلسلي",
  [localizationKeys.bidderName]: "اسم المزايد",
  [localizationKeys.biddingEndingTime]: "وقت انتهاء المزايدة",
  [localizationKeys.lastBidAmount]: "مبلغ المزايدة الأخير",
  [localizationKeys.totalBidders]: "إجمالي المزايدين",
  [localizationKeys.biddingTime]: "وقت  المزايدين",
  [localizationKeys.bidAmount]: "مبلغ المزايدة",
  [localizationKeys.startingBidAmount]: "بدء مبلغ المزايدة",
  [localizationKeys.currentBid]: " المزايدة الحالية",
  [localizationKeys.submitValueIsRequiredAndMustBeBiggerThanCurrentBid]:
    "إرسال القيمة مطلوبة ويجب أن تكون أكبر من المزايدة الحالي",
  [localizationKeys.yourAddNewSubmitValueSuccessfully]:
    "إتم تقديم العطاء الجديد بنجاح",
  [localizationKeys.congratulationsOnYourFirstBid]: "مبروك على عرضك الأول",
  [localizationKeys.editBid]: "تحرير المزايدة",
  [localizationKeys.pay]: "الدفع",
  [localizationKeys.deposit]: "إيداع",
  [localizationKeys.YouAreAboutToPlaceBidFor]: "أنت على وشك تقديم مزايدة",
  [localizationKeys.InThisAuctionPleaseNoticeThatYouWillNeedToPayA]:
    "في هذا المزاد ، يرجى ملاحظة أنك ستحتاج إلى دفع أ",
  [localizationKeys.ofThePriceAsADepositOnlyOnceSoYouCanFreelyEnjoyBidding]:
    "من السعر كوديعة مرة واحدة فقط حتى تتمكن من الاستمتاع بالمزايدة بحرية",
  [localizationKeys.endingPrice]: "السعر النهائي",
  [localizationKeys.viewAll]: "عرض الكل",
  // tab details
  [localizationKeys.shippingPolicy]: "سياسة الشحن",
  [localizationKeys.returnPolicy]: " سياسة الإرجاع",
  [localizationKeys.noReturnPolicy]: "لا توجد سياسة إرجاع",
  [localizationKeys.warrantyPolicy]: "سياسة الضمان",
  [localizationKeys.noWarrantyPolicy]: "لا يوجد سياسة ضمان",
  [localizationKeys.payment]: "الدفع",
  [localizationKeys.feedback]: "الملاحظات",
  [localizationKeys.aboutTheBrand]: "حول العلامة التجارية",
  // err
  [localizationKeys.required]: "مطلوب",
  [localizationKeys.YouHaveToIncreaseTheBiddingRateNotingThatTheLastBiddingWasInValue]:
    "يجب عليك زيادة معدل المزايدة مع ملاحظة أن آخر العطاءات كانت ذات قيمة",
  [localizationKeys.makeSureThatYouChooseItemConditionValue]:
    "تأكد من اختيار قيمة حالة العنصر",
  [localizationKeys.makeSureThatYouChooseAtLeastThreeOrMorePhotos]:
    "تأكد من اختيار ثلاث صور على الأقل أو أكثر",
  [localizationKeys.oops]:
    "عفوًا ، آسف لحدوث خطأ ما ، يرجى التأكد من صحة كل شيء والمحاولة مرة أخرى",
  // sucsess
  [localizationKeys.thisAuctionDeleteFromWatchListBeenSuccessfully]:
    "تم حذف هذا المزاد من قائمة المراقبة بنجاح",
  [localizationKeys.thisAuctionAddToWatchListBeenSuccessfully]:
    "تم إضافة هذا المزاد إلى قائمة المراقبة بنجاح",
  [localizationKeys.thePasswordHasBeenEditSuccessfully]:
    "تم تعديل كلمة المرور بنجاح",
  [localizationKeys.hasBeenDeleteSuccessfully]: "تم حذفه بنجاح",
  [localizationKeys.hasBeenMakeDefaultSuccessfully]: "تم جعله افتراضيًا بنجاح",
  [localizationKeys.imageUpdatedSuccessfully]: "تم تحديث الصورة بنجاح",
  [localizationKeys.nameHasBeenEditSuccessfully]: "تم تحرير الاسم بنجاح",
  [localizationKeys.yourAuctionSuccessfullySavedAsDraft]:
    "تم حفظ المزاد الخاص بك بنجاح كمسودة",
  [localizationKeys.yourAuctionIsCreatedSuccess]: "تم إنشاء مزادك بنجاح",
  [localizationKeys.yourProductIsSuccessfullyListed]: "تم إدراج منتجك بنجاح",
  [localizationKeys.makeSureThatYouChooseTheAuctionLocationOrCreateAnotherOne]:
    "تأكد من اختيار موقع المزاد أو إنشاء موقع آخر",
  //wallet
  [localizationKeys.Wallet]: "المحفظة",
  [localizationKeys.notifications]: "الإشعارات",
  [localizationKeys.ThereAreNoTransactionYet]: "لا توجد معاملات بعد",
  [localizationKeys.ThereAreNoNotificationsYet]: "لا توجد إشعارات بعد",
  [localizationKeys.ThereAreNoBankAccountAddedYet]:
    "لم يتم إضافة حساب بنكي بعد..!",
  [localizationKeys.accountHolderName]: "اسم صاحب الحساب :",
  [localizationKeys.bankName]: "اسم البنك :",
  [localizationKeys.bankAccountNumber]: "رقم الحساب البنكي :",
  [localizationKeys.IBANnumber]: "IBAN رقم :",
  [localizationKeys.WalletBalance]: "رصيد المحفظة ",
  [localizationKeys.Withdraw]: "ينسحب",
  [localizationKeys.Date]: "تاريخ",
  [localizationKeys.Description]: "وصف",
  [localizationKeys.Withdrawals]: "السحوبات",
  [localizationKeys.Deposits]: "الودائع",
  [localizationKeys.Balance]: "توازن",
  [localizationKeys.YourBankDetails]: "تفاصيل البنك الخاص بك",
  [localizationKeys.AddNewBankAccount]: "إضافة حساب بنكي جديد",
  [localizationKeys.EnterTheAmount]: "أدخل المبلغ",
  [localizationKeys.Amount]: "كمية",
  [localizationKeys.AmountMustBeMoreThan1AED]:
    "يجب أن يكون المبلغ أكثر من 1 درهم إماراتي",
  [localizationKeys.GoBack]: "العودة",
  [localizationKeys.SubmitWithdrawalRequest]: "إرسال طلب السحب",
  [localizationKeys.AddAccount]: "إضافة حساب",
  [localizationKeys.WithDrawalSuccessMessage]:
    "تم بنجاح! لقد تمت معالجة طلب السحب الخاص بك بنجاح. أموالك في طريقها إليك، وستصلك قريبًا. شكرًا لك على استخدام خدمتنا!",
  [localizationKeys.addAccount]: "إضافة حساب",
};

export default ar;
