import localizationKeys from "./localization-keys";

const ar = {
  // auth
  [localizationKeys.login]: "تسجيل الدخول",
  [localizationKeys.signup]: "إنشاء حساب جديد",
  [localizationKeys.loginWithApple]: "تسجيل الدخول باستخدام Apple",
  [localizationKeys.loginwithGoogle]: "تسجيل الدخول باستخدام Google",
  [localizationKeys.loginwithFacebook]: "تسجيل الدخول باستخدام Facebook",
  [localizationKeys.signupwithApple]: "تسجيل الدخول باستخدام Apple",
  [localizationKeys.signupwithGoogle]: "تسجيل الدخول باستخدام Google",
  [localizationKeys.signupwithFacebook]: "تسجيل الدخول باستخدام Facebook",
  [localizationKeys.somethingWentWrongPleaseTryAgainLater]:
    "هناك خطأ ما يرجى المحاولة مرة أخرى في او وقت لاحق",
  [localizationKeys.rememberPassword]: "تذكر كلمة المرور",
  [localizationKeys.forgetPassword]: "نسيت كلمة المرور",
  [localizationKeys.name]: "الاسم",
  [localizationKeys.email]: "البريد الإلكتروني",
  [localizationKeys.phone]: "الهاتف",
  [localizationKeys.password]: "كلمة المرور",
  [localizationKeys.iAgreetotheTermsConditions]: "أنا موافق على البنود والشروط",
  [localizationKeys.createAccount]: "إنشاء حساب",
  [localizationKeys.aVerificationMailHasBeenSent]:
    "تم إرسال بريد تحقق إلى بريدك ، يرجى التحقق منه ....",
  [localizationKeys.thePasswordHasBeenSuccessfullyChanged]:
    "تم تغيير كلمة المرور بنجاح",
  [localizationKeys.backToHome]: "العودة إلى الصفحة الرئيسية",
  [localizationKeys.resetPassword]: "إعادة تعيين كلمة المرور",
  [localizationKeys.newPassword]: "كلمة مرور جديدة",
  [localizationKeys.reEnterPassword]: "إعادة إدخال كلمة المرور",
  [localizationKeys.theEmailAddressForThisAccountHasNotYetBeenVerified]:
    "لم يتم التحقق من عنوان البريد الإلكتروني لهذا الحساب حتى الآن. يرجى التحقق من صندوق الوارد الخاص بك. إذا لم تتمكن من العثور على هذا البريد الإلكتروني",
  [localizationKeys.resendMailAgain]: "إعادة إرسال البريد مرة أخرى",
  [localizationKeys.or]: "أو",
  [localizationKeys.backToLogin]: "الرجوع إلى تسجيل الدخول",
  [localizationKeys.sentVerification]: "إرسال التحقق",
  // home
  [localizationKeys.myBids]: "مزاياداتي",
  [localizationKeys.categories]: "الفئات",
  [localizationKeys.watchlist]: "قائمة المراقبة",
  [localizationKeys.faqs]: "FAQs",
  [localizationKeys.support]: "الدعم",
  [localizationKeys.arabic]: "عربي",
  [localizationKeys.english]: "إنجليزي",
  [localizationKeys.sellNow]: "بيع الآن",
  [localizationKeys.search]: "بحث ...",
  [localizationKeys.registerNow]: "سجل الآن",
  [localizationKeys.profile]: "الملف الشخصي",
  [localizationKeys.viewDetails]: "عرض التفاصيل",
  [localizationKeys.bidNow]: "المزايدة الآن",
  [localizationKeys.popularCategories]: "الفئات الشائعة",
  [localizationKeys.results]: "من النتائج",
  [localizationKeys.seeAll]: "عرض الكل",
  [localizationKeys.brand]: "العلامة التجارية",
  [localizationKeys.sellingType]: "نوع البيع",
  [localizationKeys.auction]: "مزاد",
  [localizationKeys.buyNow]: "اشتري الآن",
  [localizationKeys.auctionState]: "حالة المزاد",
  [localizationKeys.comingSoon]: "قريباً",
  [localizationKeys.liveAuction]: "المزاد المباشر",
  [localizationKeys.location]: "الموقع",
  [localizationKeys.condition]: "الحالة",
  [localizationKeys.new]: "جديد",
  [localizationKeys.used]: "مستعملة",
  [localizationKeys.openBox]: "صندوق مفتوح",
  [localizationKeys.price]: "السعر",
  [localizationKeys.createAuctionNow]: "إنشاء مزاد الآن",
  [localizationKeys.weAreAlwaysHereToHelpYou]: "نحن دائمًا هنا لمساعدتك ...",
  [localizationKeys.subscribeNowToGetNewOffersAndUpdates]:
    "اشترك الآن للحصول على عروض وتحديثات جديدة",
  [localizationKeys.writeYourMail]: "اكتب بريدك ...",
  [localizationKeys.subscribe]: "اشتراك",
  [localizationKeys.sellingOnAllatre]: "البيع على Allatre",
  [localizationKeys.sellerCenter]: "مركز البائع",
  [localizationKeys.sellForCharity]: "بيع للجمعيات الخيرية",
  [localizationKeys.businessTools]: "أدوات العمل",
  [localizationKeys.createAuction]: "إنشاء مزاد",
  [localizationKeys.myAccount]: "حسابي",
  [localizationKeys.iamBiddingOn]: "أنا أقوم بالمزايدة على",
  [localizationKeys.iHaveBought]: "لقد اشتريت",
  [localizationKeys.bidsIHaveReceived]: "العطاءات التي استلمتها",
  [localizationKeys.iHaveSold]: "لقد بعت",
  [localizationKeys.allRightsReserved]: "جميع الحقوق محفوظة.",
  [localizationKeys.upComingAuctions]: "المزادات القادمة",
  [localizationKeys.totalBids]: "إجمالي المزادات",
  [localizationKeys.bid]: "مزاد",
  [localizationKeys.endingTime]: "نهاية الوقت",
  [localizationKeys.days]: "أيام",
  [localizationKeys.hrs]: "ساعة",
  [localizationKeys.min]: "دقيقة",
  // status
  [localizationKeys.activeNow]: "نشط الآن",
  [localizationKeys.Scheduled]: "  مجدولة",
  [localizationKeys.sold]: "مباع",
  [localizationKeys.pending]: "معلق",
  [localizationKeys.expired]: "منتهي",
  // Breadcrumb
  [localizationKeys.home]: "الصفحة الرئيسية",
  [localizationKeys.productDetails]: "تفاصيل المنتج",
  [localizationKeys.auctionDetails]: "تفاصيل المزاد",
  [localizationKeys.shippingDetails]: "تفاصيل الشحن",
  [localizationKeys.paymentDetails]: "تفاصيل الدفع",
  [localizationKeys.myAuctions]: "مزاداتي",
  [localizationKeys.activeAuctions]: "المزادات النشطة",
  [localizationKeys.scheduledAuctions]: "المزادات المجدولة",
  [localizationKeys.soldAuctions]: "المزادات المباعة",
  [localizationKeys.pendingAuctions]: "المزادات المعلقة",
  [localizationKeys.expiredAuctions]: "المزادات المنتهية",
  // create auctions
  [localizationKeys.drafts]: "المسودات",
  [localizationKeys.proceed]: "متابعة",
  [localizationKeys.successDelete]: "تم حذف مزادك من صياغتك بنجاح",
  [localizationKeys.errorDelete]:
    "عفوًا ، آسف لحدوث خطأ ما ، يرجى التأكد من صحة كل شيء والمحاولة مرة أخرى",
  [localizationKeys.areYouSureYouWantToDeleteThisDraft]:
    "هل أنت متأكد أنك تريد حذف هذه المسودة",
  [localizationKeys.cancel]: "إلغاء",
  [localizationKeys.yesDelete]: "نعم ، احذف",
  [localizationKeys.locationIsRequired]: "الموقع مطلوب",
  [localizationKeys.inOrderToFinishTheProcedureWeHaveToGetAccessTo]:
    "من أجل إنهاء الإجراء ، علينا الوصول إلى",
  [localizationKeys.yourLocationYouCanManageThemLater]:
    "موقعك. يمكنك إدارتها لاحقًا.",
  [localizationKeys.manageYouAddresses]: "إدارة عناوينك",
  [localizationKeys.country]: "دولة",
  [localizationKeys.city]: "المدينة",
  [localizationKeys.address]: "العنوان",
  [localizationKeys.addressLabel]: "علامة للعنوان",
  [localizationKeys.zipCode]: "الرمز البريدي",
  [localizationKeys.successAddLocatons]: "إضافة موقع النجاح",
  [localizationKeys.add]: "إضافة",
  [localizationKeys.selectCountry]: "تحديد البلد",
  [localizationKeys.selectCity]: "اختر المدينة",
  [localizationKeys.wirteYourAddress]: "Wirte your address",
  [localizationKeys.exHome]: "مثال:  المنزل",
  [localizationKeys.enterPostalZipCode]: "أدخل الرمز البريدي",
  // product details
  [localizationKeys.itemDetails]: "تفاصيل العنصر",
  [localizationKeys.itemName]: "اسم العنصر",
  [localizationKeys.category]: "الفئة",
  [localizationKeys.subCategory]: "فئة فرعية",
  [localizationKeys.itemDescription]: "وصف العنصر",
  [localizationKeys.writeItemDescription]: "اكتب وصف العنصر ....",
  [localizationKeys.addMedia]: "إضافة وسائط",
  [localizationKeys.from3upto5photos]: "( من 3 إلى 5 صور )",
  [localizationKeys.itemCondition]: "حالة العنصر",
  [localizationKeys.saveAsDraft]: "حفظ كمسودة",
  [localizationKeys.next]: "التالي",
};

export default ar;
