import localizationKeys from "./localization-keys";

const en = {
  // auth
  [localizationKeys.login]: "Login",
  [localizationKeys.signup]: "Sign up",
  [localizationKeys.loginWithApple]: "Login With Apple",
  [localizationKeys.loginwithGoogle]: "Login With Google",
  [localizationKeys.loginwithFacebook]: "Login With Facebook",
  [localizationKeys.signupwithApple]: "Sign up With Apple",
  [localizationKeys.signupwithGoogle]: "Sign up With Google",
  [localizationKeys.signupwithFacebook]: "Sign up With Facebook",
  [localizationKeys.rememberPassword]: "Remember Password",
  [localizationKeys.forgetPassword]: "Forget Password",
  [localizationKeys.somethingWentWrongPleaseTryAgainLater]:
    "Something went wrong, please try again later",
  [localizationKeys.name]: "Name",
  [localizationKeys.email]: "E-mail",
  [localizationKeys.phone]: "Phone",
  [localizationKeys.password]: "Password",
  [localizationKeys.iAgreetotheTermsConditions]:
    "I agree to the Terms & Conditions",
  [localizationKeys.createAccount]: "Create Account",
  [localizationKeys.aVerificationMailHasBeenSent]:
    "A verification mail has been sent to your mail please check it....",
  [localizationKeys.thePasswordHasBeenSuccessfullyChanged]:
    "The password has been successfully changed.",
  [localizationKeys.backToHome]: "Back to Home",
  [localizationKeys.resetPassword]: "Reset Password",
  [localizationKeys.newPassword]: "New Password",
  [localizationKeys.reEnterPassword]: "Re-Enter Password",
  [localizationKeys.theEmailAddressForThisAccountHasNotYetBeenVerified]:
    "The email address for this account has not yet been verified. Please check your inbox. If you cannot find this email,",
  [localizationKeys.resendMailAgain]: "Resend mail again",
  [localizationKeys.or]: "OR",
  [localizationKeys.backToLogin]: "Back to Login",
  [localizationKeys.sentVerification]: "send verification",
  // home
  [localizationKeys.myBids]: "My Bids",
  [localizationKeys.categories]: "Categories",
  [localizationKeys.watchlist]: "Watchlist",
  [localizationKeys.faqs]: "FAQs",
  [localizationKeys.support]: "Support",
  [localizationKeys.arabic]: "Arabic",
  [localizationKeys.english]: "English",
  [localizationKeys.sellNow]: "Sell Now",
  [localizationKeys.search]: "Search...",
  [localizationKeys.registerNow]: "Register Now",
  [localizationKeys.profile]: "Profile",
  [localizationKeys.viewDetails]: "View Details",
  [localizationKeys.bidNow]: "Bid Now",
  [localizationKeys.popularCategories]: "Popular Categories",
  [localizationKeys.results]: "Results",
  [localizationKeys.seeAll]: "See all",
  [localizationKeys.brand]: "Brand",
  [localizationKeys.sellingType]: "Selling Type",
  [localizationKeys.auction]: "Auction",
  [localizationKeys.buyNow]: "Buy Now",
  [localizationKeys.auctionState]: "Auction State",
  [localizationKeys.comingSoon]: "Coming Soon",
  [localizationKeys.liveAuction]: "Live Auction",
  [localizationKeys.location]: "Location",
  [localizationKeys.condition]: "Condition",
  [localizationKeys.new]: "New",
  [localizationKeys.used]: "Used",
  [localizationKeys.openBox]: "Open Box",
  [localizationKeys.price]: "Price",
  [localizationKeys.createAuctionNow]: "Create Auction Now",
  [localizationKeys.weAreAlwaysHereToHelpYou]:
    "We're Always Here To Help You...",
  [localizationKeys.subscribeNowToGetNewOffersAndUpdates]:
    "Subscribe Now to Get new offers and updates",
  [localizationKeys.writeYourMail]: "Write Your Mail...",
  [localizationKeys.subscribe]: "Subscribe",
  [localizationKeys.sellingOnAllatre]: "Selling on Allatre",
  [localizationKeys.sellerCenter]: "Seller Center",
  [localizationKeys.sellForCharity]: "Sell for charity",
  [localizationKeys.businessTools]: "Business tools",
  [localizationKeys.createAuction]: "Create Auction",
  [localizationKeys.myAccount]: "My Account",
  [localizationKeys.iamBiddingOn]: "I'm Bidding On",
  [localizationKeys.iHaveBought]: "I've Bought",
  [localizationKeys.bidsIHaveReceived]: "Bids I've Received",
  [localizationKeys.iHaveSold]: "I've Sold",
  [localizationKeys.allRightsReserved]: "All rights reserved.",
  [localizationKeys.upComingAuctions]: "Up-coming Auctions",
  [localizationKeys.totalBids]: "Total Bids",
  [localizationKeys.bid]: "Bid",
  [localizationKeys.endingTime]: "Ending Time",
  [localizationKeys.days]: "days",
  [localizationKeys.hrs]: "hrs",
  [localizationKeys.min]: "min",
  // status
  [localizationKeys.activeNow]: "Active Now",
  [localizationKeys.Scheduled]: "  Scheduled",
  [localizationKeys.sold]: "Sold",
  [localizationKeys.pending]: "Pending",
  [localizationKeys.expired]: "Expired",
  // Breadcrumb
  [localizationKeys.home]: "Home",
  [localizationKeys.productDetails]: "`product Details",
  [localizationKeys.auctionDetails]: "Auction Details",
  [localizationKeys.shippingDetails]: "Shipping Details",
  [localizationKeys.paymentDetails]: "Payment Details",
  [localizationKeys.myAuctions]: "My Auctions",
  [localizationKeys.activeAuctions]: "Active Auctions",
  [localizationKeys.scheduledAuctions]: "Scheduled Auctions",
  [localizationKeys.soldAuctions]: "Sold Auctions",
  [localizationKeys.pendingAuctions]: "Pending Auctions",
  [localizationKeys.expiredAuctions]: "Expired Auctions",
  // create auctions
  [localizationKeys.drafts]: "Drafts",
  [localizationKeys.proceed]: "Proceed",
  [localizationKeys.successDelete]:
    "Your auction has been deleted for you from drafting successfully",
  [localizationKeys.errorDelete]:
    "oops, sorry something with wrong please make sure everything is correct and try again",
  [localizationKeys.areYouSureYouWantToDeleteThisDraft]:
    "Are you sure you want to delete this draft",
  [localizationKeys.cancel]: "Cancel",
  [localizationKeys.yesDelete]: "Yes,delete",
  [localizationKeys.locationIsRequired]: "Location is required",
  [localizationKeys.inOrderToFinishTheProcedureWeHaveToGetAccessTo]:
    "In order to finish the procedure, we have to get access to",
  [localizationKeys.yourLocationYouCanManageThemLater]:
    "your location. you can manage them later .",
  [localizationKeys.manageYouAddresses]: "Manage you addresses",
  [localizationKeys.country]: "Country",
  [localizationKeys.city]: "City",
  [localizationKeys.address]: "Address",
  [localizationKeys.addressLabel]: "Address Label",
  [localizationKeys.zipCode]: "Postal code",
  [localizationKeys.successAddLocatons]: "locaton add success",
  [localizationKeys.add]: "Add",
  [localizationKeys.selectCountry]: "Select Country",
  [localizationKeys.selectCity]: "Select City",
  [localizationKeys.wirteYourAddress]: "Wirte your address",
  [localizationKeys.exHome]: "ex: Home",
  [localizationKeys.enterPostalZipCode]: "Enter postal/Zip code",
  // product details
  [localizationKeys.itemDetails]: "Item Details",
  [localizationKeys.itemName]: "Item Name",
  [localizationKeys.category]: "Category",
  [localizationKeys.subCategory]: "Sub Category",
  [localizationKeys.itemDescription]: "Item Description",
  [localizationKeys.writeItemDescription]: "Write Item Description....",
  [localizationKeys.addMedia]: "Add Media",
  [localizationKeys.from3upto5photos]: "( from 3 up to 5 photos )",
  [localizationKeys.itemCondition]: "Item Condition",
  [localizationKeys.saveAsDraft]: "Save As Draft",
  [localizationKeys.next]: "Next",
};

export default en;
