const localizationKeys = {
  // auth
  login: "login",
  signup: "signup",
  loginWithApple: "loginWithApple",
  loginwithGoogle: "loginwithGoogle",
  loginwithFacebook: "loginwithFacebook",
  signupwithApple: "signupwithApple",
  signupwithGoogle: "signupwithGoogle",
  signupwithFacebook: "signupwithFacebook",
  somethingWentWrongPleaseTryAgainLater:
    "somethingWentWrongPleaseTryAgainLater",
  name: "name",
  email: "email",
  password: "password",
  phone: "phone",
  rememberPassword: "rememberPassword",
  forgetPassword: "forgetPassword",
  iAgreetotheTermsConditions: "iAgreetotheTermsConditions",
  createAccount: "createAccount",
  aVerificationMailHasBeenSent: "aVerificationMailHasBeenSent",
  thePasswordHasBeenSuccessfullyChanged:
    "thePasswordHasBeenSuccessfullyChanged",
  backToHome: "backToHome",
  resetPassword: "resetPassword",
  newPassword: "newPassword",
  reEnterPassword: "reEnterPassword",
  theEmailAddressForThisAccountHasNotYetBeenVerified:
    "theEmailAddressForThisAccountHasNotYetBeenVerified",
  resendMailAgain: "resendMailAgain",
  or: "or",
  backToLogin: "backToLogin",
  sentVerification: "sentVerification",
  // home
  myBids: "myBids",
  categories: "categories",
  watchlist: "watchlist",
  faqs: "faqs",
  support: "support",
  arabic: "arabic",
  english: "english",
  sellNow: "sellNow",
  search: "search",
  registerNow: "registerNow",
  profile: "profile",
  viewDetails: "viewDetails",
  bidNow: "bidNow",
  buyNow: "buyNow",
  deliveryPolicy: "deliveryPolicy",
  expectedDeliveryDays: "expectedDeliveryDays",
  deliveryFees: "deliveryFees",
  locatedIn: "locatedIn",
  popularCategories: "popularCategories",
  totalBids: "totalBids",
  endingTime: "endingTime",
  bid: "bid",
  results: "results",
  seeAll: "seeAll",
  seeLess: "seeLess",
  brand: "brand",
  sellingType: "sellingType",
  auction: "auction",
  comingSoon: "comingSoon",
  liveAuction: "liveAuction",
  auctionState: "auctionState",
  location: "location",
  condition: "condition",
  new: "new",
  used: "used",
  openBox: "openBox",
  price: "price",
  createAuctionNow: "createAuctionNow",
  weAreAlwaysHereToHelpYou: "weAreAlwaysHereToHelpYou",
  subscribeNowToGetNewOffersAndUpdates: "subscribeNowToGetNewOffersAndUpdates",
  writeYourMail: "writeYourMail",
  subscribe: "subscribe",
  sellingOnAllatre: "sellingOnAllatre",
  sellerCenter: "sellerCenter",
  sellForCharity: "sellForCharity",
  businessTools: "businessTools",
  createAuction: "createAuction",
  myAccount: "myAccount",
  iamBiddingOn: "iamBiddingOn",
  iHaveBought: "iHaveBought",
  bidsIHaveReceived: "bidsIHaveReceived",
  iHaveSold: "iHaveSold",
  allRightsReserved: "allRightsReserved",
  upComingAuctions: "upComingAuctions",
  days: "days",
  hrs: "hrs",
  min: "min",
  achieveVisuallyImpressiveAuctionAttractBiddersMoreEasily:
    "achieveVisuallyImpressiveAuctionAttractBiddersMoreEasily",
  YouCanMakeYourAuctionAdPriorityAndDisplayItFirstToIncreaseBidder:
    "YouCanMakeYourAuctionAdPriorityAndDisplayItFirstToIncreaseBidder",
  participationAndAttractMoreBidders: "participationAndAttractMoreBidders",
  CreateyourAdNow: "CreateyourAdNow",
  PopularPicksPerfectChoices: "PopularPicksPerfectChoices",
  Grid: "Grid",
  List: "List",
  ThereAreAuctionsCurrentlyYouCanCreateYourOwnAuctionRightNow:
    "ThereAreAuctionsCurrentlyYouCanCreateYourOwnAuctionRightNow",
  BidWinRepeat: "BidWinRepeat",
  ComingSoonGetReadytoBid: "ComingSoonGetReadytoBid",
  DontWaitBuyNow: "DontWaitBuyNow",
  Bysubscribingyounevermissbeat: "Bysubscribingyounevermissbeat",
  Stayinformedaboutourlatestproductarrivalsspecialpromotionsandseasonalsales:
    "Stayinformedaboutourlatestproductarrivalsspecialpromotionsandseasonalsales",
  // status
  activeNow: "activeNow",
  Scheduled: "Scheduled",
  sold: "sold",
  pending: "pending",
  expired: "expired",
  // Breadcrumb
  home: "home",
  productDetails: "productDetails",
  auctionDetails: "auctionDetails",
  shippingDetails: "shippingDetails",
  paymentDetails: "paymentDetails",
  myAuctions: "myAuctions",
  activeAuctions: "activeAuctions",
  scheduledAuctions: "scheduledAuctions",
  soldAuctions: "soldAuctions",
  pendingAuctions: "pendingAuctions",
  expiredAuctions: "expiredAuctions",
  payDeposite: "payDeposite",

  // create auctions
  drafts: "drafts",
  proceed: "proceed",
  successDelete: "successDelete",
  errorDelete: "errorDelete",
  areYouSureYouWantToDeleteThisDraft: "areYouSureYouWantToDeleteThisDraft",
  cancel: "cancel",
  skip:"skip",
  YesISentIt: "YesIHaveSentIt",
  yesDelete: "yesDelete",
  locationIsRequired: "locationIsRequired",
  inOrderToFinishTheProcedureWeHaveToGetAccessTo:
    "inOrderToFinishTheProcedureWeHaveToGetAccessTo",
  yourLocationYouCanManageThemLater: "yourLocationYouCanManageThemLater",
  manageYouAddresses: "manageYouAddresses",
  country: "country",
  city: "city",
  address: "address",
  addressLabel: "addressLabel",
  zipCode: "zipCode",
  successAddLocatons: "successAddLocatons",
  add: "add",
  selectCountry: "selectCountry",
  selectCity: "selectCity",
  wirteYourAddress: "wirteYourAddress",
  exHome: "exHome",
  enterPostalZipCode: "enterPostalZipCode",
  // product details
  itemDetails: "itemDetails",
  itemName: "itemName",
  category: "category",
  subCategory: "subCategory",
  itemDescription: "itemDescription",
  writeItemDescription: "writeItemDescription",
  addMedia: "addMedia",
  from3upto5photos: "from3upto5photos",
  itemCondition: "itemCondition",
  saveAsDraft: "saveAsDraft",
  next: "next",
  // auction details
  quickAuction: "quickAuction",
  maximumDurationMustBeDay: "maximumDurationMustBeDay",
  durationMoreThanOneDayFromStartingDate:
    "durationMoreThanOneDayFromStartingDate",
  longAuction: "longAuction",
  Hrs: "Hrs",
  auctionDuration: "auctionDuration",
  scheduleBid: "scheduleBid",
  optional: "optional",
  unlessStartTimeAndDateAreChosenYourListingBecomesActiveImmediately:
    "unlessStartTimeAndDateAreChosenYourListingBecomesActiveImmediately",
  amountThatYouCanSellWithoutAuction: "AmountThatYouCanSellWithoutAuction",
  youCanGiveHereYourDeliveryRelatedPolicy:
    "youCanGiveHereYourDeliveryRelatedPolicy",
  youCanGiveHereYourReturnRelatedPolicy:
    "youCanGiveHereYourReturnRelatedPolicy",
  youCanGiveHereYourWarrantyRelatedPolicy:
    "youCanGiveHereYourWarrantyRelatedPolicy",
  includingDeliveryDateAndOthers: "includingDeliveryDateAndOthers",
  startDate: "startDate",
  howManyDaysWillItTakeForTheDeliveryAfterAuctionExpired:
    "howmanyDaysWillItTakeForTheDeliveryAfterAuctionExpired",
  time: "time",
  NumberOfDays: "numberOfDays",
  DeliveryFees: "deliveryFees",
  Amount: "amount",
  pricing: "pricing",
  startPrice: "startPrice",
  purchasingPrice: "purchasingPrice",
  PolicyDescription: "PolicyDescription",
  pleaseGiveYourDeliveryDescription: "pleaseGiveYourDeliveryDescription",
  minimum30MoreThanStartingBid: "minimum30MoreThanStartingBid",
  purchasingPriceMustBeMoreThanOrEqual30OfMinimumPrice:
    "purchasingPriceMustBeMoreThanOrEqual30OfMinimumPrice",
  whyWaitingBuyItNowOnThisPrice: "whyWaitingBuyItNowOnThisPrice",
  // shiping details
  locationDetails: "locationDetails",
  addAddress: "addAddress",
  // paymemt details
  paymentMethod: "paymentMethod",
  // profile
  online: "online",
  profileSettings: "profileSettings",
  logout: "logout",
  completeYourProfileToMakeYourActionsEasier:
    "completeYourProfileToMakeYourActionsEasier",
  completeNowMasg: " completeNowMasg",
  completeNow: " completeNow",
  personalDetails: "personalDetails",
  editPhoto: "editPhoto",
  uploadPhoto: "uploadPhoto",
  dropYourPhotoHereToInstantlyUploadIt: "dropYourPhotoHereToInstantlyUploadIt",
  save: "save",
  selectAfile: "selectAfile",
  userName: "userName",
  changePassword: "changePassword",
  editPassword: "editPassword",
  oldPassword: "oldPassword",
  edit: "edit",
  editUserName: "editUserName",
  contactUs: "contactUs",
  contactInfo: "contactInfo",
  eMail: "eMail",
  verified: "verified",
  phoneNumber: "phoneNumber",
  editPhoneNumber: "editPhoneNumber",
  loginService: "loginService",
  loginServiceMaseg: "loginServiceMaseg",
  connected: "connected",
  connectedWithApple: "connectedWithApple",
  connectWithGoogle: "connectWithGoogle",
  connectWithFacebook: "connectWithFacebook",
  addressBook: "addressBook",
  addressBookmasg: "addressBookmasg",
  the: "the",
  delete: "delete",
  makeDefault: "makeDefault",
  default: "default",
  yourWatchlist: "yourWatchlist",
  thereAreNoWatchlistYet: " thereAreNoWatchlistYet",
  // myauctions
  createNow: "createNow",
  thereAreNoAuctionsCurrentlyMakeYourFirstAuctionRightAway:
    "thereAreNoAuctionsCurrentlyMakeYourFirstAuctionRightAway",
  totalAuctions: "totalAuctions",
  total: "total",
  active: "active",
  cancelled: "cancelled",
  totalActive: "totalActive",
  totalCancel: "totalCancel",
  oppsActive: "oppsActive",
  oppsCancelled: "oppsCancelled",
  youCanCreateOne: "youCanCreateOne",
  lastPrice: "lastPrice",
  startingPrice: "startingPrice",
  startingDate: " startingDate",
  pendingDeposit: "pendingDeposit",
  purchasePrice: "purchasePrice",
  endingDate: "endingDate",
  totalScheduled: "totalScheduled",
  opsScheduled: "opsScheduled",
  totalDraft: "totalDraft",
  opsDraft: "opsDraft",
  totalSold: "totalSold",
  opsSold: "opsSold",
  totalPending: "totalPending",
  opsPending: "opsPending",
  totalExpired: "totalExpired",
  opsExpired: "opsExpired",
  watingForPaymentAuctions: "watingForPaymentAuctions",
  cancelTheAuction: "cancelTheAuction",
  Warning: "Warning",
  PaymentSelection: "PaymentSelection",
  WhichPaymentMethodWouldYouLikeToSelect:
    "WhichPaymentMethodWouldYouLikeToSelect",
  walletPayment: "walletPayment",
  onlinePayment: "onlinePayment",
  OK: "OK",
  didYouSendTheItemForDelivery: "didYouSendTheItemForDelivery",
  sendMessageToBuyer: "sendMessageToBuyer",
  Message: "Message",
  CancellAuctionWarningMessage: "CancellAuctionWarningMessage",
  ContinueToCancel: "ContinueToCancel",
  discontinue: "discontinue",
  YouSuccessfullyCancelledTheAuction: "YouSuccessfullyCancelledTheAuction",
  YouHaveSuccessfullyNotifiedTheWinner: "YouHaveSuccessfullyNotifiedTheWinner",
  // mybids
  Youarenotbiddingonanyitems: "Youarenotbiddingonanyitems",
  Checkactiveauctionstostartbidding: "Checkactiveauctionstostartbidding",
  inProgress: "inProgress",
  waitingForDelivery: "waitingForDelivery",
  completed: "completed",
  ThereIsNoBidsYetInProgressAuctionsRightNow:
    "ThereIsNoBidsYetInProgressAuctionsRightNow",
  increaseBid: "increaseBid",
  submitNewBid: " submitNewBid",
  ThereIsNoBidsYetPendingAuctionsRightNow:
    "ThereIsNoBidsYetPendingAuctionsRightNow",
  completePayment: "completePayment",
  ThereIsNoBidsYetOnWaitingForDeliveryAuctionsRightNow:
    "ThereIsNoBidsYetOnWaitingForDeliveryAuctionsRightNow",
  confirmDelivery: "confirmDelivery",
  AnyIssueWithDelivery: "AnyIssueWithDelivery",
  ThereIsNoBidsYetExpiredAuctionsRightNow:
    "ThereIsNoBidsYetExpiredAuctionsRightNow",
  ThereIsNoBidsyetCompletedAuctionsRightNow:
    "ThereIsNoBidsyetCompletedAuctionsRightNow",
  ThereIsNoBidsyetCancelledAuctionsRightNow:
    "ThereIsNoBidsyetCancelledAuctionsRightNow",
  AnyObjection: "AnyObjection",
  //deleveryIssueReportModal
  NotDeliveredYet: "NotDeliveredYet",
  ProductIsNotAsShownInPicture: "ProductIsNotSameLikePicture",
  DoesProductHaveAnyIssueWhichIsNotMentionedInTheDescription:
    "DoesProductHaveAnyIssueWhichIsNotMentionedInTheDescription",
  Others: "Others",
  tellUsYourProblem: "tellUsYourProblem",
  Description: "Description",
  UploadYourImageshere: "UploadYourImageshere",
  YouCanSelectMultipleImagestogether: "YouCanSelectMultipleImagestogether",
  Submit: "Submit",
  PleaseSelectAnyOption: "PleaseSelectAnyOption",
  PleaseGiveTheDescription: "PleaseGiveTheDescription",
  ThankYouForYourSubmission: "ThankYouForYourSubmission",
  SorryYourSubmissionHasFailedPleaseTryAgainLater:
    "SorryYourSubmissionHasFailedPleaseTryAgainLater",
  // Purchased

  Purchased: "Purchased",
  yourPurchased: "yourPurchased",
  ThereAreNoPurchasedYet: " ThereAreNoPurchasedYet",
  //  details
  reviews: "reviews",
  timeLeft: "timeLeft",
  submitBid: "submitBid",
  description: "description",
  series: "series",
  bidderName: "bidderName",
  biddingEndingTime: "biddingEndingTime",
  lastBidAmount: "lastBidAmount",
  totalBidders: "totalBidders",
  biddingTime: "biddingTime",
  bidAmount: "bidAmount",
  startingBidAmount: "startingBidAmount",
  currentBid: "currentBid",
  submitValueIsRequiredAndMustBeBiggerThanCurrentBid:
    "submitValueIsRequiredAndMustBeBiggerThanCurrentBid",
  yourAddNewSubmitValueSuccessfully: "yourAddNewSubmitValueSuccessfully",
  congratulationsOnYourFirstBid: "congratulationsOnYourFirstBid",
  editBid: "editBid",
  pay: "pay",
  deposit: "deposit",
  YouAreAboutToPlaceBidFor: " YouAreAboutToPlaceBidFor",
  InThisAuctionPleaseNoticeThatYouWillNeedToPayA:
    "InThisAuctionPleaseNoticeThatYouWillNeedToPayA",
  ofThePriceAsADepositOnlyOnceSoYouCanFreelyEnjoyBidding:
    "ofThePriceAsADepositOnlyOnceSoYouCanFreelyEnjoyBidding",
  endingPrice: "endingPrice",
  viewAll: "viewAll",
  // tab details
  shippingPolicy: "shippingPolicy",
  returnPolicy: "returnPolicy",
  warrantyPolicy: "warrantyPolicy",
  payment: "payment",
  feedback: "feedback",
  aboutTheBrand: "aboutTheBrand",
  // err
  required: "required",
  makeSureThatYouChooseItemConditionValue:
    "makeSureThatYouChooseItemConditionValue",
  makeSureThatYouChooseAtLeastThreeOrMorePhotos:
    "makeSureThatYouChooseAtLeastThreeOrMorePhotos",
  oops: "oops",
  mustOneUppercaseOneLowercaseOneNumberAndOneSpecialCaseCharacter:
    "mustOneUppercaseOneLowercaseOneNumberAndOneSpecialCaseCharacter",
  notMatch: "notMatch",
  YouHaveToIncreaseTheBiddingRateNotingThatTheLastBiddingWasInValue:
    "YouHaveToIncreaseTheBiddingRateNotingThatTheLastBiddingWasInValue",
  // sucsess
  thisAuctionDeleteFromWatchListBeenSuccessfully:
    "thisAuctionDeleteFromWatchListBeenSuccessfully",
  thisAuctionAddToWatchListBeenSuccessfully:
    "thisAuctionAddToWatchListBeenSuccessfully",
  thePasswordHasBeenEditSuccessfully: "thePasswordHasBeenEditSuccessfully",
  hasBeenDeleteSuccessfully: "hasBeenDeleteSuccessfully",
  hasBeenMakeDefaultSuccessfully: "hasBeenMakeDefaultSuccessfully",
  thePhoneNumberHasBeenEditSuccessfully:
    "thePhoneNumberHasBeenEditSuccessfully",
  nameHasBeenEditSuccessfully: "nameHasBeenEditSuccessfully",
  uploadImageHasbeenSuccessfully: "uploadImageHasbeenSuccessfully",
  yourAuctionSaveAsDraftedSuccess: "yourAuctionSaveAsDraftedSuccess",
  yourAuctionIsCreatedSuccess: "yourAuctionIsCreatedSuccess",
  makeSureThatYouChooseTheAuctionLocationOrCreateAnotherOne:
    "makeSureThatYouChooseTheAuctionLocationOrCreateAnotherOne",
  //wallet
  Wallet: "Wallet",
  ThereAreNoTransactionYet: "ThereAreNoTransactionYet",
  WalletBalance: "WalletBalance",
  Withdraw: "Withdraw",
  Date: "Date",
  Withdrawals: "Withdrawals",
  Deposits: "Deposits",
  Balance: "Balance",
  ThereAreNoBankAccountAddedYet: "ThereAreNoBankAccountAddedYet",
  accountHolderName: "accountHolderName",
  bankName: "bankName",
  bankAccountNumber: "Bank Account Number:",
  IBANnumber: "IBANnumber",
  YourBankDetails: "YourBankDetails",
  EnterTheAmount: "EnterTheAmount",
  Amount: "Amount",
  AmountMustBeMoreThan1AED: "AmountMustBeMoreThan1AED",
  AddNewBankAccount: "AddNewBankAccount",
  GoBack: "GoBack",
  SubmitWithdrawalRequest: "SubmitWithdrawalRequest",
  AddAccount: "AddAccount",
  WithDrawalSuccessMessage: "WithDrawalSuccessMessage",
};

export default localizationKeys;
