const localizationKeys = {
  // auth
  login: "login",
  signup: "signup",
  loginWithApple: "loginWithApple",
  loginwithGoogle: "loginwithGoogle",
  loginwithFacebook: "loginwithFacebook",
  signupwithApple: "signupwithApple",
  signupwithGoogle: "signupwithGoogle",
  signupwithFacebook: "signupwithFacebook",
  somethingWentWrongPleaseTryAgainLater:
    "somethingWentWrongPleaseTryAgainLater",
  name: "name",
  email: "email",
  password: "password",
  phone: "phone",
  rememberPassword: "rememberPassword",
  forgetPassword: "forgetPassword",
  iAgreetotheTermsConditions: "iAgreetotheTermsConditions",
  createAccount: "createAccount",
  aVerificationMailHasBeenSent: "aVerificationMailHasBeenSent",
  thePasswordHasBeenSuccessfullyChanged:
    "thePasswordHasBeenSuccessfullyChanged",
  backToHome: "backToHome",
  resetPassword: "resetPassword",
  newPassword: "newPassword",
  reEnterPassword: "reEnterPassword",
  theEmailAddressForThisAccountHasNotYetBeenVerified:
    "theEmailAddressForThisAccountHasNotYetBeenVerified",
  resendMailAgain: "resendMailAgain",
  or: "or",
  backToLogin: "backToLogin",
  sentVerification: "sentVerification",
  // home
  myBids: "myBids",
  categories: "categories",
  watchlist: "watchlist",
  faqs: "faqs",
  support: "support",
  arabic: "arabic",
  english: "english",
  sellNow: "sellNow",
  search: "search",
  registerNow: "registerNow",
  profile: "profile",
  viewDetails: "viewDetails",
  bidNow: "bidNow",
  buyNow: "buyNow",
  popularCategories: "popularCategories",
  totalBids: "totalBids",
  endingTime: "endingTime",
  bid: "bid",
  results: "results",
  seeAll: "seeAll",
  brand: "brand",
  sellingType: "sellingType",
  auction: "auction",
  comingSoon: "comingSoon",
  liveAuction: "liveAuction",
  auctionState: "auctionState",
  location: "location",
  condition: "condition",
  new: "new",
  used: "used",
  openBox: "openBox",
  price: "price",
  createAuctionNow: "createAuctionNow",
  weAreAlwaysHereToHelpYou: "weAreAlwaysHereToHelpYou",
  subscribeNowToGetNewOffersAndUpdates: "subscribeNowToGetNewOffersAndUpdates",
  writeYourMail: "writeYourMail",
  subscribe: "subscribe",
  sellingOnAllatre: "sellingOnAllatre",
  sellerCenter: "sellerCenter",
  sellForCharity: "sellForCharity",
  businessTools: "businessTools",
  createAuction: "createAuction",
  myAccount: "myAccount",
  iamBiddingOn: "iamBiddingOn",
  iHaveBought: "iHaveBought",
  bidsIHaveReceived: "bidsIHaveReceived",
  iHaveSold: "iHaveSold",
  allRightsReserved: "allRightsReserved",
  upComingAuctions: "upComingAuctions",
  days: "days",
  hrs: "hrs",
  min: "min",
  // status
  activeNow: "activeNow",
  Scheduled: "Scheduled",
  sold: "sold",
  pending: "pending",
  expired: "expired",
};

export default localizationKeys;
